services:
  app_test:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db_test/rust_market_test
      - RUST_LOG=debug
    depends_on:
      - db_test
    command: cargo test

  db_test:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rust_market_test
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev database
